---
title: "`r params$doc_title`"
author: "Brian Erly, MD MPH; Shannon O'Brien, MD MPH"
date: "`r Sys.Date()`"
output:
  html_document:
    theme:
      bootswatch: sandstone
params:
  county: DENVER
  doc_title: Polio Vaccine Rate Report
---

```{r setup, include=FALSE}
source(file = "r_scripts/01_libraries and functions.R")
source(file = "r_scripts/00_secrets.R")

county_tract_ids <- read_csv("data/county_tract_ids.csv")

options(tigris_use_cache = TRUE)

suppressMessages({
geom_with_age <- get_acs(
  geography = "tract",
  state = "CO",
  variables = c(
    Under_18 = "B09001_001"

  ),
  year = 2017,
  geometry = TRUE
) %>%
  mutate(TractID = as.numeric(GEOID)) %>%
  mutate(Under_18 = estimate) %>%
  select(TractID, NAME,Under_18,geometry)
}
)

Colorado_data_mr <- read_csv("data/Colorado_data_mr.csv",
  show_col_types = FALSE)

polio_rate <- read_csv("data/CDPHE Data/Polio Vaccine Rates.csv",
  show_col_types = FALSE) %>%
  select(1:5) %>%
  rename(TractID = fips,
         Tot_pop = totpop,
         Polio_3plus_5_9 = `3vax_polio_age_5_9_ciis`) %>%
  mutate(rate_census = pmin(Polio_3plus_5_9/pop_age_5_9_census, 1),
         rate_ciis = pmin(Polio_3plus_5_9/pop_age_5_9_ciis, 1),
           susceptible_census = pmax(pop_age_5_9_census - `Polio_3plus_5_9`,0),
         susceptible_ciis = pmax(pop_age_5_9_ciis - `Polio_3plus_5_9`,0),
         quntile_census = ntile(rate_census,5),
         quntile_ciis = ntile(rate_ciis,5)
  )


Polio_Vaccine_Index <- polio_rate %>%
    full_join(geom_with_age) %>%
  left_join(county_tract_ids) %>%
  left_join(Colorado_data_mr) %>%
  mutate(geometry = sf::st_transform(geometry,4326))


```
## Introduction

```{r intro,echo = FALSE, results = 'asis'}
glue::glue(
  "
  **This is the pediatric polio vaccine modeling report for Colorado**  
  
  There are {nrow(Polio_Vaccine_Index)} census tracts in {params$county} County. The median pediatric vaccination rate for Colorado census tracts is {median(Polio_Vaccine_Index$rate_3plus_doses_div_ciis_pop)}%, with a range of {min(Polio_Vaccine_Index$rate_3plus_doses_div_ciis_pop)} to {max(Polio_Vaccine_Index$rate_3plus_doses_div_ciis_pop)}%. 
  
  "
) %>%
  print()

```

  The charts shown below illustrate the range of polio vaccination in Colorado by census tract.


```{r fig1, echo=FALSE, results = 'asis', fig.height = 8, fig.width = 8, fig.align = "center"}
suppressMessages({

co_basemap <- ggmap::get_stamenmap(bbox = c(left = -109.060253,
                                            bottom = 36.992426,
                                            right = -102.041524,
                                            top = 41.003444), zoom=8, maptype = 'toner')
})
p1 <- ggmap(co_basemap) +
       # coord_sf(crs = sf::st_crs(4326))+
  geom_sf(data = Polio_Vaccine_Index,
          aes(fill = rate_census,geometry = geometry,
                            tract_name = NAME,

                            population = pop_age_5_9_census,
                            vaccination_rate = rate_census,

          # text = sprintf("Vaccination Rate: %s<br>Letter: %s", a, b),
            alpha = 0.5),
          inherit.aes = FALSE)+
    theme_void() +
    scale_fill_viridis(option = "inferno",
      breaks=c(40,60,80,100), name="Vaccination Rate", 
      guide = guide_legend( keyheight = unit(5, units = "mm"), 
                            keywidth=unit(12, units = "mm"), 
                            label.position = "bottom", 
                            title.position = 'top', nrow=1) ) +
  labs(title = "",
       subtitle = "") +
  theme(
    legend.position = "bottom"
  )

fig <- plotly::ggplotly(p1,
                        tooltip = c("tract_name","population","vaccination_rate")) %>%
                         plotly::style(.,hoveron = "fill")
  

fig

```

```{r}
susceptible_points <- Polio_Vaccine_Index %>%
  summarize(points = sf::st_sample(geometry, size = susceptible_ciis))

p2 <- ggplot() +
  geom_sf(data= Polio_Vaccine_Index,
          aes(fill = rate_ciis,
              geometry=geometry))+
  geom_sf(aes(geometry=points),data = susceptible_points,
          size = 0.5,alpha = 0.5) 
 
 plotly::ggplotly(p2)

```